old test apps /mysite0/mysite/django/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

old test apps /mysite0/mysite/djangoappengine/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

old test apps /mysite0/mysite/gproject/urls.py
from django.conf.urls import patterns, include, url

from gproject.views import QFeed

from gproject import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

  
	#for the root directory folder
    url(r'^$', views.index, name='index'),
    #for login
    url(r'^login/$', views.login, name='login'),
    #for searching
    url(r'^search/$', views.search, name='search'),
    #for uploading content
    url(r'^upload/$', views.upload, name='upload'),
    #for downloading content
    url(r'^download/(?P<pk>.+)$', views.download, name= 'download'),
    #for adding a question
    url(r'^add_question/$', views.add_question, name='add_question'),
    #for viewing count of view
    url(r'^add_answer/(?P<question_id>\d+)/$', views.add_answer, name='add_answer'),
    #for viewing count of view
    url(r'^edit_answer/(?P<answer_id>\d+)/$', views.edit_answer, name='edit_answer'),
    
    url(r'^(?P<question_id>\d+)/$', views.question_detail, name='question_detail'),
    
    url(r'^(?P<question_id>\d+)/edit_question$', views.edit_question, name='edit_question'),
  
    url(r'^(?P<question_id>\d+)/vote_q/$', views.vote_question, name='vote_question'),
    
    url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
   
    url(r'^(?P<question_id>\d+)/vote_a/$', views.vote_answer, name='vote_answer'),
    #for the RSS FEED for questions!
    url(r'^(?P<question_id>\d+)/feed$', QFeed()),
)

old test apps /mysite0/mysite/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
#adding extra django views
from django.conf.urls import patterns
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

import dbindexer

handler500 = 'djangotoolbox.errorviews.server_error'

# django admin
admin.autodiscover()

# search for dbindexes.py in all INSTALLED_APPS and load them
dbindexer.autodiscover()

#updating URL Patterns! for login and making the views
urlpatterns = patterns('',
    ('^_ah/warmup$', 'djangoappengine.views.warmup'),
    ('^_ah/login_required$', 'djangoappengine.views.warmup'),
    ('^$', 'gproject.views.index'),
    ('^admin/', include(admin.site.urls)),
    ('^gproject/', include('gproject.urls', namespace="gproject")),
)

old test apps /mysite0/mysite/gproject/models.py
from django.db import models
from google.appengine.api import users
from django.contrib.auth.models import User
import datetime


class UploadModel(models.Model):
    file = models.FileField(upload_to='uploads/%Y/%m/%d/%H/%M/%S/')
    filename = models.CharField(max_length=600, default=' ')

    def __str__(self):         
        return self.filename

class Question(models.Model):
    question_text = models.TextField()
    pub_date = models.DateTimeField(default = datetime.datetime.now())
    user = models.ForeignKey(User, null=True, blank=True)
    votes = models.IntegerField(default=0)
    tags = models.CharField(max_length=500, default=' ')
    image = models.ForeignKey(UploadModel, null=True, blank=True)

    def __str__(self):           
        return self.question_text

class Answer(models.Model):
    answer_text = models.TextField()
    pub_date = models.DateTimeField(default = datetime.datetime.now())
    user = models.ForeignKey(User, null=True, blank=True)
    votes = models.IntegerField(default=0)
    image = models.ForeignKey(UploadModel, null=True, blank=True, default=0)
    question_id=models.ForeignKey(Question, null=True, blank=True)

    def __str__(self):            
        return self.answer_text

class Vote(models.Model):
    vote_text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, null=True, blank=True)
    question_id=models.ForeignKey(Question)
    answer_id=models.ForeignKey(Answer, null=True, blank=True, default=0)
    NONE = 0
    UP = 1
    DOWN = -1
    CHOICES = ( 
        (NONE, 'None'),
        (UP, 'Up'),
        (DOWN, 'Down'),
    )
    up_or_down = models.IntegerField(choices=CHOICES, default=0)

    def __str__(self):              # __unicode__ on Python 2
        return self.vote_text

old test apps /mysite0/mysite/gproject/forms.py
from django import forms
from django.forms import ModelForm
from gproject.models import Question, Answer, Vote, UploadModel

class CreateQuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'tags', 'image']

class CreateAnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['answer_text', 'image']

class EditQuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'tags', 'image']

class EditAnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['answer_text', 'image']

class UploadForm(forms.ModelForm):
    class Meta:
        model = UploadModel
        fields = ['file', 'filename']

old test apps /mysite0/mysite/gproject/views.py
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from filetransfers.api import prepare_upload, serve_file
from django.views.generic import TemplateView
from django.contrib.syndication.views import Feed

from google.appengine.api import users
from google.appengine.ext import webapp

import webapp2
import datetime
import re

from gproject.models import Question, Answer, Vote, UploadModel
from gproject.forms import CreateQuestionForm, CreateAnswerForm, EditQuestionForm, EditAnswerForm, UploadForm

#I can use google as my app provider
providers = {
    'Google'   : 'https://www.google.com/accounts/o8/id',
}

#creating a list of questions
#it will show 10 questions per page
def index(request):
    user = users.get_current_user()
    if user:  
        logged_in = True
        test_user(user)
    else:  
        user = ""
        logged_in = False
 
    highest_voted_q_list = Question.objects.order_by('-pub_date')
    paginator = Paginator(highest_voted_q_list, 10) 
    page = request.GET.get('page')
    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)

    context = { 'highest_voted_q_list': questions, 'user': user, 'logged_in': logged_in }
    return render(request, 'gproject/index.html', context)

#here we define what we use to search
#what we will be going through is the number of tags
def search(request):
    user = users.get_current_user()
    search_term = request.POST['search']
    if user:  
        logged_in = True
        test_user(user)
    else:  
        user = ""
        logged_in = False
  
    highest_voted_q_list = Question.objects.order_by('-pub_date')[:10]
    search_results = []
    regex = re.compile(r'^(.+\s+)*%s(\s+.+)*$'%search_term)
    for q in highest_voted_q_list:
        tag_list = q.tags
        if regex.match(q.tags):
            search_results.append(q.id)
    highest_voted_q_list = Question.objects.filter(pk__in=search_results)
    context = { 'highest_voted_q_list': highest_voted_q_list, 'user': user, 'logged_in': logged_in, 'search_results':search_results}
    return render(request, 'gproject/index.html', context)

#we are using this to now login
#what makes this unqiue is that we have to look for any http calls
#check is user is already signed in or not
def login(request):
    user = users.get_current_user()
    response = HttpResponse()
    for name, uri in providers.items():
        provider = name
    if user:  
        response.write('Welcome Friend <em>%s</em>! [<a href="%s">sign out</a>]' % (
                user.nickname(), users.create_logout_url(request.get_full_path())))
        test_user(user)
    else:     
        response.write('Sign in: ')

        for name, uri in providers.items():
            response.write('[<a href="%s">%s</a>]' % (
                users.create_login_url(federated_identity=uri), name))
    response.write('<br><a href="/">home</a>')
    return response

#we also created a look to check is we have any users already logged in
#this is important because we need to give them the option to log in or log out

def test_user(user):
    user = users.get_current_user()
    if user:  
        try:
            db_user = User.objects.get(username=user.nickname())
        except ObjectDoesNotExist:
            u = User.objects.create_user(user.nickname())
            u.save()
    return db_user

#this is the massive infor dump for our question
def question_detail(request, question_id):
    user = users.get_current_user()
   
    if user:  
        logged_in = True
        test_user(user)
    else:  
        user = ""
        logged_in = False
   #lets get our list of votes!
    question = get_object_or_404(Question, pk=question_id)
    sum = sum_votes(question, 0)
    question.votes=sum
    question.save()
    highest_voted_a_list = question.answer_set.order_by('-votes')
    context = { 'highest_voted_a_list': highest_voted_a_list, 'question': question, 'user': user, 'logged_in': logged_in }
    return render(request, 'gproject/question_detail.html', context)

#what happens when we finish voting?
def results(request, question_id):
    user = users.get_current_user()
    if user:  
        logged_in = True
        test_user(user)
    else:  
        user = ""
        logged_in = False
        #we get back our list of results
        #we return our highest voted list
    question = get_object_or_404(Question, pk=question_id)
    highest_voted_a_list = question.answer_set.order_by('-votes')
    context = { 'highest_voted_a_list': highest_voted_a_list, 'question': question, 'user': user, 'logged_in': logged_in }
    return render(request, 'gproject/results.html', context)


#we need to see what teh user selected
#there is only two choice up or down
def vote_question(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    user = users.get_current_user()
    if user:  
        logged_in = True
        db_user = test_user(user) 
        
        if 'UP' in request.POST:
            vote = 1
        else:
            vote = -1
        try:
            v = Vote.objects.get(question_id=q, user=db_user, answer_id=0)
        except ObjectDoesNotExist:
            v = Vote(question_id=q, user=db_user, pub_date=datetime.datetime.now(), vote_text=user.nickname()+", "+q.question_text)
            v.save()
       #checking if user has voted up, summing results
        v.up_or_down = vote
        v.save()
        sum = sum_votes(q, 0)
        q.votes=sum
        q.save()
    else:  
        user = ""
        logged_in = False

    return HttpResponseRedirect(reverse('gproject:results', args=(q.id,)))


def vote_answer(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    
    user = users.get_current_user()
    if user:  
        logged_in = True
        db_user=test_user(user) 
        
        if 'UP' in request.POST:
            vote = 1
        else:
            vote = -1 
        try:
            selected_answer = q.answer_set.get(pk=request.POST['answer'])
            try:
                v = Vote.objects.get(question_id=q, answer_id=selected_answer, user=db_user)
            except ObjectDoesNotExist:
                v = Vote(question_id=q, answer_id=selected_answer, user=db_user, pub_date=datetime.datetime.now(), vote_text=user.nickname()+", "+q.question_text+", "+selected_answer.answer_text)
                v.save()
            
            v.up_or_down = vote
            v.save() 
           
            sum = sum_votes(q, selected_answer)
            selected_answer.votes=sum
            selected_answer.save()
        except (KeyError, Answer.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'gproject/question_detail.html', {
                'question': q,
                'error_message': "You didn't select an answer.",
            })
    else:
        user = ""
        logged_in = False
    return HttpResponseRedirect(reverse('gproject:results', args=(q.id,)))

#we need to calculate the votes again

def sum_votes(question_id, answer_id):
    sum = 0
    positive_arr = Vote.objects.filter(question_id=question_id, answer_id=answer_id, up_or_down=1)
    negative_arr = Vote.objects.filter(question_id=question_id, answer_id=answer_id, up_or_down=-1)
    sum = len(positive_arr) - len(negative_arr)
    return sum

#get and post methods all over again!
#get question text from the form
def add_question(request):
    user = users.get_current_user()
    if user:  
        logged_in = True
        db_user = test_user(user)

        #adding in the published date paramters
        #if there is no form then what could happen is that a user can 
        #input text into a form
      
        if request.method == 'POST':
            form = CreateQuestionForm(request.POST)
            if form.is_valid():
                question = form.save(commit=False)
                question.user = db_user
                question.pub_date = datetime.datetime.now()  
                question.pub_date = datetime.datetime.now()
                new_text = make_links_and_photos(question.question_text)
                question.question_text = new_text             
                question.save()
                highest_voted_a_list = question.answer_set.order_by('-votes')
                context = { 'highest_voted_a_list': highest_voted_a_list, 'question': question, 'user': user, 'logged_in': logged_in }
                return render(request, 'gproject/question_detail.html', context)
        
        else:
            form = CreateQuestionForm()
    else:  
        user = ""
        logged_in = False
    return render(request, 'gproject/add_question.html', {'form': form, 'user':user , 'logged_in': logged_in})


#same as question but er are creating a form for checking and saving the answer
# if no answer there will be a blank form

def add_answer(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    user = users.get_current_user()
    if user:  
        logged_in = True
        db_user = test_user(user)
        
        if request.method == 'POST':
           
            form = CreateAnswerForm(request.POST)
            if form.is_valid():
                answer = form.save(commit=False)
                answer.user = db_user
                answer.question_id = question
                answer.pub_date = datetime.datetime.now()
                new_text = make_links_and_photos(answer.answer_text)
                answer.answer_text = new_text
                answer.save()
                question = answer.question_id

old test apps /mysite0/mysite/gproject/templates/gproject/add_answer.html
{% if logged_in %}
	Welcome Friend! <em> {{ user }}</em>! <a href="{% url 'gproject:login' %}">sign out?</a>
	<form action="{% url 'gproject:add_answer' question.id %}" method="post"
	    {% csrf_token %}
	    {{ form }}
	    <input type="submit" value="Submit" />
	</form>
	<a href="{% url 'gproject:upload' %}">upload</a>
{% else %}
	'Have you even signed in yet? If you didn't how do you think you can even an answer. <a href="{% url 'gproject:login' %}"> sign in </a>
{% endif %}
<a href="{% url 'gproject:index' %}">home</a>

old test apps /mysite0/mysite/gproject/templates/gproject/add_question.html
{% if logged_in %}
	Hi! <em> {{ user }}</em>! <a href="{% url 'gproject:login' %}">sign out?</a>
	<form action="{% url 'gproject:add_question' %}" method="post"
	    {% csrf_token %}
	    {{ form }}
	    <input type="submit" value="Submit" />
	</form>
	<a href="{% url 'gproject:upload' %}">upload (keep it clean!)</a>
{% else %}
	'Welcome stranger! You need to be signed to add questions. <a href="{% url 'gproject:login' %}"> sign in? </a>
{% endif %}
<a href="{% url 'gproject:index' %}">home</a>

old test apps /mysite0/mysite/gproject/templates/gproject/edit_answer.html
{% if logged_in %}
	Welcome Stranger! <em> {{ user }}</em>! <a href="{% url 'gproject:login' %}">sign out?</a>
	{% if is_author %}
		<form action="{% url 'gproject:edit_answer' answer.id %}" method="post"
		    {% csrf_token %}
		    {{ form }}
		    <input type="submit" value="Submit" />
		</form>
	<a href="{% url 'gproject:upload' %}">upload (keep it clean!)</a>
	{% else %}
		Did you make this answer? No, so you can't edit. 
	{% endif %}
{% else %}
	'Did you sign? If you didn't you need to be signed in to edit a answer. So do it! <a href="{% url 'gproject:login' %}"> sign in </a>
{% endif %}
<a href="{% url 'gproject:index' %}">home</a>

old test apps /mysite0/mysite/gproject/templates/gproject/edit_question.html
{% if logged_in %}
	Hello <em> {{ user }}</em>! <a href="{% url 'gproject:login' %}">sign out</a>
	{% if is_author %}
		<form action="{% url 'gproject:edit_question' question.id %}" method="post"
		    {% csrf_token %}
		    {{ form }}
		    <input type="submit" value="Submit" />
		</form>
	<a href="{% url 'gproject:upload' %}">upload</a>
	{% else %}
		Did you make this question? No, so you can't edit. 
	{% endif %}
{% else %}
	'Did you sign? If you didn't you need to be signed in to edit a question. So do it! <a href="{% url 'gproject:login' %}"> sign in? </a>
{% endif %}
<a href="{% url 'gproject:index' %}">home</a>

old test apps /mysite0/mysite/gproject/templates/gproject/index.html
{% if logged_in %}
    Welcome Stranger <em> {{ user }}</em>! <a href="{% url 'gproject:login' %}">sign out?</a>
    <a href="{% url 'gproject:add_question' %}">add question!</a>
{% else %}
    'Welcome stranger <a href="{% url 'gproject:login' %}"> sign in please </a>
{% endif %}
<form action="{% url 'gproject:search' %}" method="post">
    {% csrf_token %}
    <input type="text" name="search" value="search tags" />
    <input type="submit" name="Submit" value="Submit" />
</form>
<a href="{% url 'gproject:upload' %}">upload(keep it clean!)</a>
{% if  highest_voted_q_list %}
<ul>
    {% for question in highest_voted_q_list %}
    <li><a href="{% url 'gproject:question_detail' question.id %}">Question {{question.id}}</a> {{ question.question_text|truncatechars:500|safe }}</a> -- {{ question.votes }} vote{{ question.votes|pluralize }}</li>
    <hr>
    {% endfor %}
</ul>
{% else %}
<p>No questions :( (add some more)</p>
{% endif %}
<div class="pagination">
    <span class="step-links">
        {% if highest_voted_q_list.has_previous %}
        <a href="?page={{ highest_voted_q_list.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
            Page {{ highest_voted_q_list.number }} of {{ highest_voted_q_list.paginator.num_pages }}.
        </span>
        {% if highest_voted_q_list.has_next %}
        <a href="?page={{ highest_voted_q_list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
<a href="{% url 'gproject:index' %}">home</a>

old test apps /mysite0/mysite/gproject/templates/gproject/question_detail.html
{% if logged_in %}
	Welcome stranger <em> {{ user }}</em>! <a href="{% url 'gproject:login' %}">sign out?</a>
	<a href="{% url 'gproject:add_answer' question.id %}">add an answer</a>
	<a href="{% url 'gproject:edit_question' question.id %}">edit a question</a>
	<form action="{% url 'gproject:vote_question' question.id %}" method="post">
		{% csrf_token %}
		<input type="radio" name="question" id="question{{ question.id }}" value="{{ question.id }}" />
		<label for="question.id"><h1>{{ question.question_text|safe }} : {{ question.votes }} vote{{ question.votes|pluralize }} </h1></label><br />
		<input type="submit" name="UP" value="UP" />
		<input type="submit" name="DOWN" value="DOWN" />
	</form>
	<h2>Tags:  {{ question.tags }}  </h2>
	{% if question.image != None %}
		Image:
	    <img src="{% url 'gproject:download' pk=question.image.pk %}">
	    <a href="{% url 'gproject:download' pk=question.image.pk %}">uploaded image</a>
    {% endif %}
    <hr>
	{% if  highest_voted_a_list %}
		<form action="{% url 'gproject:vote_answer' question.id %}" method="post">
			{% csrf_token %}
			{% for answer in highest_voted_a_list %}
			    <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}" />
			    <label for="answer{{ forloop.counter }}">{{ answer.answer_text|safe }} : {{ answer.votes }} vote{{ answer.votes|pluralize }}  <a href="{% url 'gproject:edit_answer' answer.id %}">edit answer</a></label><br />
				{% if answer.image != None %}
				    Image:
			    	<img src="{% url 'gproject:download' pk=answer.image.pk %}">
			   		<a href="{% url 'gproject:download' pk=answer.image.pk %}">link to uploaded image</a>
			   	{% endif %}
			 <hr>
			{% endfor %}
			<br>
			<input type="submit" name="UP" value="UP" />
			<input type="submit" name="DOWN" value="DOWN" />
		</form>
	{% else %}
	    <p>No answers are available.</p>
	{% endif %}
{% else %}
	'Welcome Stranger! <a href="{% url 'gproject:login' %}"> You wanna vote?</a>
	<h1>{{ question.question_text|safe }} -- {{ question.votes }} vote{{ question.votes|pluralize }} </h1>
	<h2>Tags:  {{ question.tags }}  </h2>
	<hr> 
	{% if  highest_voted_a_list %}
		<ul>
		{% for answer in highest_voted_a_list %}
		    <li>{{ answer.answer_text|safe }} : {{ answer.votes }} vote{{ answer.votes|pluralize }}</li>
		<hr>
		{% endfor %}
		</ul>
	{% else %}
	    <p>No answers are available.</p>
	{% endif %}
{% endif %}

<a href="{% url 'gproject:index' %}">home</a>

old test apps /mysite0/mysite/gproject/templates/gproject/results.html
{% if logged_in %}
	Hello <em> {{ user }}</em>! <a href="{% url 'gproject:login' %}">sign out?</a>
{% else %}
	'Welcome Stranger <a href="{% url 'gproject:login' %}"> sign in? </a>
{% endif %}
<h1>{{ question.question_text|safe }} -- {{ question.votes }} vote{{ question.votes|pluralize }}</h1>
{% if question.image != None %}
	Image:
    <img src="{% url 'gproject:download' pk=question.image.pk %}">
    <a href="{% url 'gproject:download' pk=question.image.pk %}">link to uploaded image</a>
{% endif %}
<hr>
{% if  highest_voted_answer_list %}
	<ul>
	{% for answer in highest_voted_a_list %}
	    <li>{{ answer.answer_text|safe }} -- {{ answer.votes }} vote{{ answer.votes|pluralize }}</li>
    	{% if answer.image != None %}
		    Image:
	    	<img src="{% url 'gproject:download' pk=answer.image.pk %}">
	   		<a href="{% url 'gproject:download' pk=answer.image.pk %}">link to uploaded image</a>
   		{% endif %}
   	<hr>
	{% endfor %}
	</ul>
{% else %}
    <p>No answers. :( (add some more)</p>
{% endif %}
{% if logged_in %}
	<a href="{% url 'gproject:question_detail' question.id %}">Would you like to vote again?</a>
{% endif %}
<a href="{% url 'gproject:index' %}">home</a>

old test apps /mysite0/mysite/gproject/templates/gproject/upload.html
{% load filetransfers %}
<form action="{{ upload_url }}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% render_upload_data upload_data %}
  <table>{{ form }}</table>
  <input type="submit" value="Upload" />
</form>
<h1>Uploaded Files</h1>
<ul>
  {% for upload in uploads %}
    <li>
      {% url 'gproject:download' pk=upload.pk as fallback_url %}
      <a href="{% firstof upload.file|public_download_url fallback_url %}"> {{ upload.filename }}</a>
      ({{ upload.file.size|filesizeformat }})
    </li>
  {% endfor %}
</ul>
<a href="{% url 'gproject:index' %}">home</a>